export const sample_pets = [
    {
        id: '1',
        name: 'Криси',
        gender: 'Мъжки',
        age: '2',
        imageUrl: 'https://images.pexels.com/photos/57416/cat-sweet-kitty-animals-57416.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        parents: [3, 4],
        siblings: [2, 5, 6],
        children: [],
        breed: 'улична превъзходна',
        colors: ['оранжев', 'бял']
    },
    {
        id: '2',
        name: 'Лори',
        gender: 'Женска',
        age: '2',
        imageUrl: 'https://cdn.pixabay.com/photo/2014/11/30/14/11/cat-551554_640.jpg',
        parents: [3, 4],
        siblings: [1, 2, 5, 6],
        children: [7],
        breed: 'улична превъзходна',
        colors: ['оранжев', 'бял']
    },
    {
        id: '3',
        name: 'Сиса',
        gender: 'Женска',
        age: '4',
        imageUrl: 'https://cdn.pixabay.com/photo/2016/02/10/16/37/cat-1192026_640.jpg',
        parents: [8, 9],
        siblings: [10],
        children: [1, 2, 5, 6],
        breed: 'улична превъзходна',
        colors: ['сив', 'бял']
    },
    {
        id: '4',
        name: 'Навчо',
        gender: 'Мъжки',
        age: '4',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/81/Persialainen.jpg',
        parents: [7, 8],
        siblings: [11],
        children: [1, 2, 5, 6],
        breed: 'персийска',
        colors: ['сив', 'риж']
    },
    {
        id: '5',
        name: 'Сивушака',
        gender: 'Женска',
        age: '2',
        imageUrl: 'https://cats.com/wp-content/uploads/2022/03/gray-cats-compressed.jpg',
        parents: [3, 4],
        siblings: [1, 2, 6],
        children: [],
        breed: 'улична',
        colors: ['сив']
    },
    {
        id: '6',
        name: 'Черньо',
        gender: 'Мъжки',
        age: '2',
        imageUrl: 'https://cdn.britannica.com/25/172925-050-DC7E2298/black-cat-back.jpg',
        parents: [3, 4],
        siblings: [1, 2, 6],
        children: [],
        breed: 'уличен превъзходен',
        colors: ['черен']
    },
    {
        id: '7',
        name: 'Зуза',
        gender: 'Женски',
        age: '1',
        imageUrl: 'https://cdn.pixabay.com/photo/2014/11/30/14/11/cat-551554_640.jpg',
        parents: [1, 2],
        siblings: [],
        children: [],
        breed: 'уличен превъзходен',
        colors: ['бял']
    },
    {
        id: '8',
        name: 'Котаракът в чизми',
        gender: 'Мъжки',
        age: '6',
        imageUrl: 'https://i.pinimg.com/564x/73/44/c6/7344c6eb343fb4c6ad415a579c35fd83.jpg',
        parents: [10],
        siblings: [10],
        children: [],
        breed: 'уличен превъзходен',
        colors: ['риж']
    },
    {
        id: '9',
        name: 'Kити',
        gender: 'Женски',
        age: '6',
        imageUrl: 'https://preview.redd.it/kitty-softpaws-from-puss-in-boots-the-last-wish-2022-v0-0hhnjvwfueba1.jpg?width=450&format=pjpg&auto=webp&s=b76884f1eb17d4d66815b23e4f90d630e766c9bf',
        parents: [10],
        siblings: [10],
        children: [],
        breed: 'уличен превъзходен',
        colors: ['черен']
    },
    {
        id: '10',
        name: 'Неизвестно',
        gender: 'Женски',
        age: 'Неизвестно',
        imageUrl: 'https://pngimg.com/d/pusheen_PNG43.png',
        parents: [10],
        siblings: [10],
        children: [],
        breed: 'уличен превъзходен',
        colors: ['черен']
    },
];